[project]
name = "candy-land"
version = "2025.0"
description = "Candy Land game simulation"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "ruff>=0.16.5",
]

[tool.ruff.lint]
extend-select = ["ANN", "E", "F", "FURB", "I", "PERF", "Q", "RSE", "RUF", "S", "UP"]
